[general]
serverName = DESKTOP-GDO0KDV
pass4SymmKey = $7$arCwu9DSOhtT9UUqx841lap+emzIE0r8+qbJ7b7EsvHa3XYRMn28gg==

[sslConfig]
sslPassword = $7$vkwyprg2hWnGYrK6qqIy7JKykEVGepu05LOWW5fPuj7fr37/e4I2ew==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[license]
active_group = Trial
manager_uri = http://127.0.0.1:1337
